# Generated by Django 5.2.15 on 2026-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_userprofile_full_name_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='Скидка 35%%'),
        ),
    ]
