# Generated by Django 5.2.15 on 2026-07-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discounted',
        ),
    ]
